Нужно больше функций
htmlacademy-javascript/2072197-keksobooking-26 pull request #2
Opened 2022-06-08 10:15 UTC by A1exLove

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/javascript/26/user/2072197/tasks/6)

:boom: https://htmlacademy-javascript.github.io/2072197-keksobooking-26/2/

2022-06-08 16:44 UTC, DmitryMarkov requested changes
Надо исправить ошибки линтера https://github.com/htmlacademy-javascript/2072197-keksobooking-26/runs/6795896541?check_suite_focus=true

2022-06-08 16:44 UTC, DmitryMarkov commented on Readme.md
> +
Этого не должно быть тут, дублируется

2022-06-08 18:45 UTC, A1exLove commented on Readme.md
> +
Как можно удалить коммит из родительского репозитория?

2022-06-08 19:05 UTC, DmitryMarkov commented on Readme.md
> +
не надо удалять коммит, надо удалить дублированный текст

2022-06-08 19:06 UTC, DmitryMarkov commented on js/main.js
> +getRandomDigits();
уверен, что хорошая идея - запускать функции без аргументов?

2022-06-08 19:33 UTC, A1exLove commented on js/main.js
> +getRandomDigits();
Добавил аргументы.

2022-06-08 19:41 UTC, DmitryMarkov commented on Readme.md
> +
можно мастер из репозитория академии спуллить в свой мастер и в эту ветку

2022-06-08 19:57 UTC, A1exLove commented on Readme.md
> +
Сделано

2022-06-08 19:59 UTC, DmitryMarkov commented on Readme.md
> +
и запушить коммит )

2022-06-08 20:09 UTC, A1exLove commented on Readme.md
> +
Запушил

2022-06-08 20:11 UTC, DmitryMarkov commented on Readme.md
> +
Не вижу. Оно должно быть здесь: https://github.com/htmlacademy-javascript/2072197-keksobooking-26/pull/2/commits а в файле быть не должно

2022-06-08 20:12 UTC, A1exLove commented on Readme.md
> +
Сразу после исправления текста путём пулла из репозитория, гит не дал запушить изменения, пришлось вручную немного изменить текст в index.html

2022-06-08 20:16 UTC, A1exLove commented on Readme.md
> +
Текст у меня дублировался в ветке module1-task1

2022-06-08 20:35 UTC, DmitryMarkov commented on Readme.md
> +
но ты можешь его удалить сейчас

2022-06-08 20:53 UTC, A1exLove commented on Readme.md
> +
У меня в VSCode при сохранении дублируется текст index.html

2022-06-09 07:18 UTC, DmitryMarkov approved these changes

2022-06-09 07:18 UTC, merged